package-lock.json, package.json, server/db/models/index.js, server/db/models/product.js, server/db/models/product.spec.js
=> updated with model and association

server/db/models/category.js, server/db/models/index.js
added Category Model and associations
=> Category model #47

package-lock.json, server/api/index.js, server/api/products.js, server/api/users.js
=> Product get routes

script/seed.js, server/db/models/category.js, server/db/models/index.js
=> Seed the database #12

client/store/index.js, client/store/productReducer.js, client/store/productReducer.spec.js, server/db/models/index.js
=> Product reducer

client/store/index.js, client/store/productReducer.js, client/store/productReducer.spec.js
=> added loading and error scripts

client/components/ProductList.js, client/components/SingleProduct.js, client/components/index.js, client/routes.js, client/store/productReducer.js, package-lock.json
The Products List page now works
=> Create product components #4

client/store/productReducer.js
=> filter should work for real now

client/store/productReducer.js, server/api/categories.js, server/api/categories.spec.js, server/api/index.js
=> Category routes

client/components/ProductItem.js, client/components/ProductList.js, client/components/user-home.js
=> ProductList now maps again properly

server/api/users.js, server/api/users.spec.js
=> updated to include user routes and test

server/db/models/index.js, server/db/models/lineItem.js
=> updated to include line item model

client/components/sidebar.js, server/auth/google.js
=> Cleaned up Tabs/Indentation on Sidebar (sorry!)

server/db/models/index.js, server/db/models/order.js, server/db/models/product.js
Let me know if the fields are good to go! Also just added a minimum value of 0 for quantity in the product model
=> created order model and associations uncommented

server/db/models/user.js
=> fixed oauth hopefully

server/api/authorize.js, server/api/categories.js, server/api/categories.spec.js, server/index.js
Ok guys I obviously don't expect anyone to see this tonight, but the category routes are done, and I made a piece of middleware to test whether or not someone is authorized to use something, it just occurred to me that the id part is kinda stupid with categories so i'll probs take that out at some point but it does work, I've tested. The test all fail but that's cause of the middleware if you take that out they all pass, and when i'm logged in as admin on Postico everything works.  As an update I have done a lot of work on the product routes but i also terribly broke something so now I can't get anything to load yay! so i'll fix that tomorrow
=> category routes all set and made authorize middleware

server/api/authorize.js, server/api/categories.js, server/api/categories.spec.js, server/api/products.js, server/api/products.spec.js, server/index.js
=> all Product route working

client/components/navbar.js, script/seed.js, server/api/products.js
Deleted Authorize from routes in product that don't need it
Changed emails in seed file to email instead of gmail 
added Trip Catalog to navBar
=> Admin abilities

server/api/index.js, server/api/reviews.js, server/api/reviews.spec.js, server/api/users.js
=> updated to include review routes and tests

client/components/AdminCategories.js, client/components/AdminProductMini.js, client/components/AdminProducts.js, client/components/SingleCategory.js, client/components/index.js, client/components/navbar.js, client/routes.js, client/store/categoryReducer.js, client/store/productReducer.js, script/seed.js
=> Can Delete Products

client/components/Cart.js, client/store/cartReducer.js, server/api/orders.js
added functionality to dropdown in cart to change quantity, added helper functions to clean up post/orders route, eager loading reviews with orders, creates order in db when a guest checks out (so admin can see all orders)
=> change quantity in cart, creates order in db for guests on checkout

client/components/AdminOrders.js, client/components/LineItem.js, client/components/Order.js, client/components/index.js, client/routes.js, client/store/index.js, client/store/ordersReducer.js, script/seed.js, server/api/orders.js
=> Order Status

client/components/AddToCartButton.js, server/api/orders.js
=> change quantity of product at checkout

client/store/adminReducer.js, client/store/cartReducer.js, client/store/categoryReducer.js, client/store/ordersReducer.js, server/api/products.js
=> Routes for new and improved filter

client/store/adminReducer.js, client/store/cartReducer.js, client/store/categoryReducer.js, client/store/ordersReducer.js
=> Reducer edits

client/components/ReviewForm.js, client/components/SingleProduct.js, client/store/reviewReducer.js, server/api/authorize.js, server/api/checkIfUser.js, server/api/index.js, server/api/orders.js, server/api/reviews.js
=> Remove reviews #123

client/components/AddToCartButton.js, client/components/Cart.js, client/components/navbar.js, client/components/sidebar.js, client/store/productReducer.js, package-lock.json, server/api/orders.js
=> Edited Filter Products

client/components/ProductItem.js, client/components/navbar.js, script/seed.js, server/api/products.js
=> this thing is the worst

client/components/LineItem.js, client/components/Order.js, client/components/navbar.js, package-lock.json, server/api/orders.js
=> Orders are working again

client/components/SingleProduct.js, package-lock.json, package.json, server/api/reviews.js, server/db/models/index.js
=> updated to remove console logs
